#!/bin/bash

# aside - create timestamped log entries on the fly

BR="\n"
BREAK="\n\n"
TAB="\t"
BUL="\t\t*"

DATE=`date +"%Y%m%d"`
TIME=`date +"%T"`
HEAD=`date +"%Y %b %d"`

DIR=~/Documents/log
FILE=$DIR/$DATE.md

if [ ! -d $DIR ]; then
  mkdir -p $DIR
fi

if [ ! -f $FILE ]; then
  printf "# $HEAD" >> $FILE
fi

# set time header
printf "\n\n## $TIME\n\n" >> $FILE

# open logfile for writing
vi $FILE
