#!/bin/bash

# flatcircle - fetch and view past log entries
# depends on node package ttab

SUBJ=${1:-general}

DIR=~/Documents/logs/$SUBJ
if [ ! -d $DIR ]; then
  mkdir -p $DIR
fi

YESTERDAY=`date -j -v -1d +"%Y%m%d"`
FILE=$DIR/$YESTERDAY.md
if [ -f $FILE ]; then
  `ttab -w less $FILE`
fi

LASTWEEK=`date -j -v -1w +"%Y%m%d"`
FILE=$DIR/$LASTWEEK.md
if [ -f $FILE ]; then
  `ttab -w less $FILE`
fi

LASTMONTH=`date -j -v -1m +"%Y%m%d"`
FILE=$DIR/$LASTMONTH.md
if [ -f $FILE ]; then
  `ttab -w less $FILE`
fi

THREEMONTHSAGO=`date -j -v -3m +"%Y%m%d"`
FILE=$DIR/$THREEMONTHSAGO.md
if [ -f $FILE ]; then
  `ttab -w less $FILE`
fi

LASTYEAR=`date -j -v -1y +"%Y%m%d"`
FILE=$DIR/$LASTYEAR.md
if [ -f $FILE ]; then
  `ttab -w less $FILE`
fi
